; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
	fastled/FastLED@^3.6.0
    adafruit/Adafruit GFX Library@^1.11.11
	adafruit/Adafruit SSD1306@^2.5.7
	someweisguy/esp_dmx@^4.1.0
    arduino-libraries/Ethernet@^2.0.2
	hideakitai/ArtNet@^0.9.2

[env:led_tube]
board = seeed_xiao_esp32s3
build_flags = -D DEVICE_MODE=0

[env:bridge]
board = esp32dev
build_flags = -D DEVICE_MODE=1


[env:test_reliability_bridge]
board = esp32dev
build_flags = -D DEVICE_MODE=1 -D WDMX_SILENT
lib_ldf_mode = deep+
build_src_filter = -<*> +<WirelessDmx.cpp> +<../test_programs/reliability_test/bridge.cpp>

[env:test_reliability_tube]
board = seeed_xiao_esp32s3
build_flags = -D DEVICE_MODE=0
lib_ldf_mode = deep+
build_src_filter = -<*> +<../test_programs/reliability_test/tube.cpp>